### ISSUE TITLE
Version 1.3.0 for MC 1.21 can't take off

### ISSUE THREAD

**Issue by XavierBit** [kennethsible/elytrapitch#2]
Hi!
Thanks for adding the options I suggested so quickly!

When trying to take off I have a problem as the space bar double tap just forces me into a 44 degree angle and I splat my face into the ground :)

What am I missing?

EDIT: Sorry, seems the glide lock was messing with me. I got it working and it's just perfect now!

**Comment by kennethsible** [comment]
I would check that your pitch isn't locked to 44 degrees by pressing the 'R' key (default).

**Comment by kennethsible** [comment]
I'm going to add an Assisted Flight toggle to the settings menu that will enable/disable the features ported from FlightHelper. In addition, I will add optional messages that say when the pitch is locked/unlocked and when the HUD element is visible/hidden.

**Comment by XavierBit** [comment]
you are the man! I'm so happy that you are actively developing this mod. Thank you so much for your dedication.

**Comment by kennethsible** [comment]
I pushed a commit (3d12d0d) that adds the new settings I discussed above. I'll be releasing 1.3.1 on Modrinth and CurseForge sometime tonight. I am just happy that people are interested in using this mod! I made it for myself and my friends as a side project, but what kind of mod author would I be if I didn't continue to maintain it!
