### ISSUE TITLE
[Feature request] Add functionality to set the flying mode before activating Elytra

### ISSUE THREAD

**Issue by r1klz** [kennethsible/elytrapitch#4]
Hey! Thank you for developing this mod. It's very useful!

So, in the current version, we can lock the pitch when we're still in the ground (since *Assisted Flight* is enabled), but the other functions like *Snap to Ascend/Descend/Glide* we can't. I guess if we have a function to this, it would be perfect. Imagine if an user has a 60% keyboard and sets the keys to `F[0-9]` and they can't activate in time (as flying with Elytra) or a 100% keyboard with keys set to numpad?

What do you think about it?

**Comment by kennethsible** [comment]
I think it would be easier to change the behavior to overwrite the locked pitch with the takeoff angle in this situation, that way the player won't accidentally fly into the ground if their pitch was previously locked to a descent angle.

**Comment by r1klz** [comment]
Yeah, I agree with that. But how exactly it'll be? The mod will know when the player is on the ground or the player will manually lock it?

See: my point in that implementation was just to have the possibility to lock - or actually set and then lock - the modes before you are flying with Elytra, so you can set the angle before taking off.

**Comment by kennethsible** [comment]
I made the following change: whatever angle the player is locked to at takeoff will be overwritten with the angle they are currently looking at (e5caa6c). You can always change your pitch again after takeoff with the snap keybindings, but this way no one will fly straight into the ground anymore. You'll see these changes in the next release (v1.4.0).

**Comment by r1klz** [comment]
It's nice. It wasn't exactly what I proposed, but it's ok. My idea was about snapping the screen to ascend while still in the ground when the player presses the *Snap to Ascend* keybind. But maybe that would be a little too invasive to the gameplay?
I think that now the default keybindings was set to *Not Bound*, it would be ok for the snap feature to have this behaviour.

Just for pointing out: removing `client.player.isFallFlying()` from https://github.com/kennethsible/elytrapitch/blob/main/src/main/java/fatalflare/elytrapitch/ElytraPitch.java#L84-L88 would do that?

But anyways! +1 for the durability feature. Thank you!
